# Setup
title:        Coders for Causes
tagline:      Student Developers for Charities and Not-For-Profits
baseurl:      ""
paginate:     1

# About/contact
#author:
#  name:       Author name
#  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

facebook_username: codersforcauses
github_username: codersforcauses
site_repo_link: "https://github.com/codersforcauses/codersforcauses.github.io"

#Others
permalink: /:title/
markdown: kramdown

relative_permalinks: false
