# Setup
title:        Coders for Causes
tagline:      Student Developers for Charities and Not-For-Profits
baseurl:      ""
paginate:     1

# About/contact
#author:
#  name:       Author name
#  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#includes

#Others
permalink: /:title/
markdown: kramdown

relative_permalinks: false
